# Generated by Django 5.2.4 on 2025-07-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('published_date', models.DateField(default='2012-05-05')),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
