# Generated by Django 5.2.4 on 2025-08-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images/'),
        ),
    ]
